# Generated by Django 3.1.5 on 2021-11-18 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_delete_post'),
        ('posts', '0002_imagepostmodel_textlikemodel_textpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='textlikemodel',
            name='post',
        ),
        migrations.RemoveField(
            model_name='textlikemodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='ImagePostModel',
        ),
        migrations.DeleteModel(
            name='TextLikeModel',
        ),
        migrations.AddField(
            model_name='textpost',
            name='likes',
            field=models.ManyToManyField(to='posts.LikeModel'),
        ),
    ]
