# Generated by Django 3.1.5 on 2021-11-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20211118_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='likes',
            field=models.ManyToManyField(to='posts.LikeModel'),
        ),
        migrations.AddField(
            model_name='textpost',
            name='date_published',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
