# Generated by Django 3.2.8 on 2021-12-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20211118_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='likes',
            field=models.ManyToManyField(blank=True, to='posts.LikeModel'),
        ),
        migrations.AlterField(
            model_name='textpost',
            name='likes',
            field=models.ManyToManyField(blank=True, to='posts.LikeModel'),
        ),
    ]
