# Generated by Django 3.2.8 on 2021-10-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='profile_images/default.png', upload_to='profile_images'),
        ),
    ]
