# Generated by Django 3.2.8 on 2021-10-27 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='posts',
        ),
        migrations.AddField(
            model_name='profile',
            name='posts',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.post'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='profile_images/default.svg', upload_to='profile_images'),
        ),
    ]
