# Generated by Django 3.1.5 on 2021-11-18 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_alter_profile_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
