# Generated by Django 3.2.8 on 2021-12-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
